### ISSUE TITLE
JSON parse failed

### ISSUE THREAD

**Issue by Haui74** [leoclee/7-segment-clock#6]
Hi!
My Clock doesnt show the correct time. The serial Monitor says:
request sent
headers received
getTimeZoneOffset: JSON parse failed!
9c
{
   "dstOffset" : 3600,
   "rawOffset" : 3600,
   "status" : "OK",
   "timeZoneId" : "Europe/Berlin",
   "timeZoneName" : "Central European Summer Time"
}
saving config
Google Api and IPstack Api checked thousand times ;)

**Comment by leoclee** [comment]
The error is caused by the 2 extra characters in the JSON response body ("9c" in the example posted by @Haui74 and "99" in my own tests). I'm not exactly sure why this started happening, but I could not see the extra characters when testing the Google Maps API GET request in a browser or with curl, so I assume it must be something in the ESP8266 http client in combination with a change on Google's side. For now, I've fixed the issue by reading up until the JSON begins by looking for the opening curly brace.
